enum WebPanel {
    static let index = #"""
    <!doctype html>
    <html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Lustre local downloads</title>
    <style>
    :root{color-scheme:dark;--ink:#f1eee8;--muted:#a9aaa5;--panel:#181b1c;--canvas:#101313;--line:#303737;--accent:#df6f4d;--green:#9bc48b;--red:#ee8074;font-family:ui-rounded,"SF Pro Rounded",-apple-system,BlinkMacSystemFont,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink)}main{max-width:1240px;margin:auto;padding:36px 24px 72px}.eyebrow{font:12px ui-monospace,SFMono-Regular,monospace;color:var(--accent);letter-spacing:.13em;text-transform:uppercase}h1{font-size:clamp(32px,6vw,54px);letter-spacing:-.055em;margin:7px 0 8px}.lede{color:var(--muted);margin:0;max-width:650px}section{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}.top{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:end;margin:28px 0 16px}.form{display:grid;grid-template-columns:1.7fr .8fr 1.2fr auto;gap:10px;align-items:end}.field{display:grid;gap:7px;font-size:12px;color:var(--muted);font-weight:700;letter-spacing:.06em;text-transform:uppercase}input{min-width:0;width:100%;background:#0e1010;border:1px solid #414848;border-radius:8px;padding:11px;color:var(--ink);font:14px ui-monospace,SFMono-Regular,monospace}button{border:0;border-radius:8px;min-height:42px;padding:0 14px;background:var(--accent);color:#21100b;font:700 13px inherit;cursor:pointer}button.secondary{background:#2a3030;color:var(--ink);border:1px solid #465050}button.danger{color:#ffb6af;background:#432522}button:disabled{opacity:.5;cursor:not-allowed}.grid{display:grid;grid-template-columns:1.35fr .85fr;gap:16px}.jobs{display:grid;gap:8px}.job{display:grid;grid-template-columns:10px 1fr auto;gap:12px;align-items:start;padding:13px 0;border-bottom:1px solid var(--line)}.job:last-child{border-bottom:0}.dot{width:8px;height:8px;border-radius:50%;background:var(--muted);margin-top:6px}.running .dot{background:var(--accent);box-shadow:0 0 0 4px #df6f4d22}.completed .dot{background:var(--green)}.failed .dot,.cancelled .dot{background:var(--red)}.url{font:12px ui-monospace,SFMono-Regular,monospace;color:var(--muted);overflow-wrap:anywhere}.meta{font-size:13px;margin:4px 0;color:var(--ink)}.small{font-size:12px;color:var(--muted)}.actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.actions button{min-height:30px;padding:0 9px;font-size:11px}.log{height:440px;overflow:auto;background:#0d0f0f;border-radius:9px;padding:12px;font:12px/1.5 ui-monospace,SFMono-Regular,monospace}.entry{padding:5px 0;border-bottom:1px solid #252a2a;color:#c8cdca}.entry.error{color:#ff9f94}.entry time{color:#737b79;margin-right:8px}.empty{color:var(--muted);padding:24px 0}#notice{min-height:20px;color:var(--muted);font-size:13px;margin:10px 0}.connected{color:var(--green)}@media(max-width:850px){.top,.grid,.form{grid-template-columns:1fr}.actions{justify-content:flex-start}}
    </style></head><body><main>
    <div class="eyebrow">Lustre · local control</div><h1>Downloads, in view.</h1><p class="lede">Queue a source, select its destination, and follow resolver and worker events without leaving your browser.</p>
    <section class="top"><label class="field">Agent token<input id="token" type="password" autocomplete="off" placeholder="Run: lustre token"></label><button class="secondary" id="connect">Connect</button></section>
    <section><div class="form"><label class="field">Source URL<input id="url" type="url" placeholder="https://…"></label><label class="field">Quality<input id="quality" placeholder="Optional exact label"></label><label class="field">Destination<select id="remote"><option value="local">Local folder</option></select></label><label class="field">Download folder<input id="destination" placeholder="Default: ~/Downloads/Lustre"></label><button class="secondary" id="choose">Choose folder</button></div><div id="notice">Connect to the local agent to begin.</div><button id="queue">Queue download</button></section>
    <section><div class="eyebrow">Remote destinations</div><div class="form"><label class="field">Name<input id="server-name" placeholder="Seedbox"></label><label class="field">WebDAV HTTPS URL<input id="server-url" type="url" placeholder="https://server.example/webdav"></label><label class="field">Username<input id="server-user"></label><label class="field">Password<input id="server-password" type="password" autocomplete="new-password"></label><label class="field">Remote folder<input id="server-path" placeholder="/Videos/Lustre"></label><label class="field">TLS exception<input id="server-allow-invalid" type="checkbox">Trust an invalid certificate for this exact server</label><button id="save-server">Save WebDAV destination</button></div><div id="destinations" class="small">Connect to manage remote destinations.</div></section>
    <div class="grid"><section><div class="eyebrow">Queue</div><div id="jobs" class="jobs"><div class="empty">No job data yet.</div></div></section><section><div class="eyebrow">Worker log</div><div id="log" class="log"><div class="empty">Select a job to inspect its event log.</div></div></section></div>
    </main><script>
    const el=id=>document.getElementById(id);let selected=null,connected=false,timer=null;
    const api=async(path,body,method=body?'POST':'GET')=>{const token=el('token').value.trim();if(!/^[A-Za-z0-9+/=]+$/.test(token))throw Error('Paste only the token printed by `lustre token`.');const r=await fetch(path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(r.status===401?'The token was rejected. Run `lustre token` and paste only its single output line.':data.error||'Request failed');return data};
    const note=(text,error=false)=>{el('notice').textContent=text;el('notice').className=error?'':'connected'};
    function render(jobs){const root=el('jobs');if(!jobs.length){root.innerHTML='<div class="empty">No queued downloads.</div>';return}if(!selected||!jobs.some(j=>j.id===selected))selected=jobs[0].id;root.innerHTML=jobs.map(j=>`<article class="job ${j.status}" data-id="${j.id}"><span class="dot"></span><div><strong>${escapeHTML(j.status)}</strong><div class="meta">${escapeHTML(j.message)}</div><div class="url">${escapeHTML(j.sourcePageURL)}</div>${progressText(j)}<div class="small">${escapeHTML(j.destination)} · ${new Date(j.updatedAt).toLocaleString()}</div></div><div class="actions">${buttons(j)}</div></article>`).join('');root.querySelectorAll('.job').forEach(x=>x.onclick=e=>{if(e.target.tagName==='BUTTON')return;selected=x.dataset.id;render(jobs);renderLog(jobs.find(j=>j.id===selected))});root.querySelectorAll('button[data-action]').forEach(b=>b.onclick=async()=>{try{await api(`/v1/jobs/${b.dataset.id}/action`,{action:b.dataset.action});await refresh()}catch(e){note(e.message,true)}});renderLog(jobs.find(j=>j.id===selected))}
    const buttons=j=>j.status==='queued'?`<button class="secondary" data-id="${j.id}" data-action="pause">Pause</button><button class="danger" data-id="${j.id}" data-action="cancel">Cancel</button>`:j.status==='running'?`<button class="secondary" data-id="${j.id}" data-action="pause">Pause</button><button class="danger" data-id="${j.id}" data-action="cancel">Cancel</button>`:j.status==='paused'?`<button data-id="${j.id}" data-action="resume">Resume</button><button class="danger" data-id="${j.id}" data-action="cancel">Cancel</button>`:j.status==='failed'||j.status==='cancelled'?`<button data-id="${j.id}" data-action="retry">Retry</button>`:j.status==='verificationRequired'?`<button data-id="${j.id}" data-action="retry">Retry</button><button class="danger" data-id="${j.id}" data-action="cancel">Cancel</button>`:'';
    const formatBytes=value=>{if(typeof value!=='number'||value<0)return '';const units=['B','KiB','MiB','GiB'];let index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return `${value.toFixed(index?1:0)} ${units[index]}`};
    const progressText=j=>{if(j.status!=='running')return '';const downloaded=formatBytes(j.downloadedBytes);const total=formatBytes(j.totalBytes);if(typeof j.progress==='number')return `<div class="meta">Downloading ${Math.round(Math.min(1,Math.max(0,j.progress))*100)}%${downloaded&&total?` · ${downloaded} / ${total}`:''}</div>`;return `<div class="meta">Downloading${downloaded?` · ${downloaded}${total?` / ${total}`:' (total size unavailable)'}`:'…'}</div>`};
    function renderLog(job){const root=el('log');const entries=job?.logs||[];root.innerHTML=entries.length?entries.map(x=>`<div class="entry ${x.level}"><time>${new Date(x.timestamp).toLocaleTimeString()}</time>${escapeHTML(x.message)}</div>`).join(''):'<div class="empty">No worker events for this job.</div>';root.scrollTop=root.scrollHeight}
    const escapeHTML=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
    async function refresh(){if(!connected)return;try{render(await api('/v1/jobs'))}catch(e){note(e.message,true)}}
    async function refreshDestinations(){const destinations=await api('/v1/destinations');const select=el('remote');const previous=select.value;select.innerHTML='<option value="local">Local folder</option>'+destinations.map(d=>`<option value="webdav:${d.id}">${escapeHTML(d.name)} · WebDAV</option>`).join('');select.value=Array.from(select.options).some(x=>x.value===previous)?previous:'local';el('destinations').innerHTML=destinations.length?destinations.map(d=>`<div>${escapeHTML(d.name)} · ${escapeHTML(d.baseURL)}${escapeHTML(d.remotePath)} <button class="secondary" data-test-id="${d.id}">Test connection</button> <button class="danger" data-destination-id="${d.id}">Remove</button></div>`).join(''):'No remote destinations saved.';document.querySelectorAll('button[data-test-id]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const result=await api('/v1/destinations/'+b.dataset.testId+'/test',{});note(result.message)}catch(e){note(e.message,true)}finally{b.disabled=false}});document.querySelectorAll('button[data-destination-id]').forEach(b=>b.onclick=async()=>{try{await api('/v1/destinations/'+b.dataset.destinationId,null,'DELETE');await refreshDestinations();note('Remote destination removed.')}catch(e){note(e.message,true)}})}
    el('connect').onclick=async()=>{try{render(await api('/v1/jobs'));connected=true;await refreshDestinations();note('Connected. Live status refreshes every 2 seconds.');clearInterval(timer);timer=setInterval(refresh,2000)}catch(e){connected=false;note(e.message,true)}};
    el('choose').onclick=async()=>{try{const result=await api('/v1/folders/select',{});el('destination').value=result.path;note('Destination folder selected.')}catch(e){note(e.message,true)}};
    el('remote').onchange=()=>{const isLocal=el('remote').value==='local';el('destination').disabled=!isLocal;el('choose').disabled=!isLocal};
    el('save-server').onclick=async()=>{try{await api('/v1/destinations/webdav',{name:el('server-name').value,baseURL:el('server-url').value,username:el('server-user').value,password:el('server-password').value,remotePath:el('server-path').value,allowInvalidCertificate:el('server-allow-invalid').checked});el('server-password').value='';await refreshDestinations();note('Remote WebDAV destination saved. The password is stored in Keychain.')}catch(e){note(e.message,true)}};
    el('queue').onclick=async()=>{try{const destination=el('remote').value==='local'?(el('destination').value||'local'):el('remote').value;const job=await api('/v1/jobs',{sourcePageURL:el('url').value,preferredQualityLabel:el('quality').value||null,destination});selected=job.id;note('Queued. The worker will resolve and begin transfer.');await refresh()}catch(e){note(e.message,true)}};
    </script></body></html>
    """#
}