import { bigint, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const createdAt = timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
export const lustreAccounts = pgTable("lustre_accounts", { id: uuid("id").defaultRandom().primaryKey(), authProvider: text("auth_provider").notNull(), authSubject: text("auth_subject").notNull(), createdAt, disabledAt: timestamp("disabled_at", { withTimezone: true }) }, (table) => [uniqueIndex("lustre_accounts_provider_subject").on(table.authProvider, table.authSubject)]);
export const lustreDevices = pgTable("lustre_devices", { id: uuid("id").defaultRandom().primaryKey(), accountID: uuid("account_id").notNull().references(() => lustreAccounts.id), publicKey: text("public_key").notNull(), keyThumbprint: text("key_thumbprint").notNull(), displayName: text("display_name").notNull(), platform: text("platform").notNull(), agentVersion: text("agent_version").notNull(), createdAt, lastAuthenticatedAt: timestamp("last_authenticated_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }) }, (table) => [uniqueIndex("lustre_devices_thumbprint").on(table.keyThumbprint), index("lustre_devices_account").on(table.accountID)]);
export const lustrePairingChallenges = pgTable("lustre_pairing_challenges", { id: uuid("id").defaultRandom().primaryKey(), accountID: uuid("account_id").notNull().references(() => lustreAccounts.id), codeHash: text("code_hash").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), consumedAt: timestamp("consumed_at", { withTimezone: true }), createdAt }, (table) => [uniqueIndex("lustre_pairing_challenges_code_hash").on(table.codeHash), index("lustre_pairing_challenges_account").on(table.accountID)]);
export const lustreDeviceEnrollments = pgTable("lustre_device_enrollments", { id: uuid("id").defaultRandom().primaryKey(), pairingChallengeID: uuid("pairing_challenge_id").notNull().references(() => lustrePairingChallenges.id), publicKey: text("public_key").notNull(), keyThumbprint: text("key_thumbprint").notNull(), displayName: text("display_name").notNull(), platform: text("platform").notNull(), agentVersion: text("agent_version").notNull(), nonce: text("nonce").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), consumedAt: timestamp("consumed_at", { withTimezone: true }), createdAt });
export const lustreDeviceSessionChallenges = pgTable("lustre_device_session_challenges", { id: uuid("id").defaultRandom().primaryKey(), deviceID: uuid("device_id").notNull().references(() => lustreDevices.id), nonce: text("nonce").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), consumedAt: timestamp("consumed_at", { withTimezone: true }), createdAt });
export const lustreDeviceAuditEvents = pgTable("lustre_device_audit_events", { id: uuid("id").defaultRandom().primaryKey(), accountID: uuid("account_id").notNull().references(() => lustreAccounts.id), deviceID: uuid("device_id").notNull().references(() => lustreDevices.id), kind: text("kind").notNull(), metadata: jsonb("metadata").notNull().default({}), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull() });
export const lustreRateLimits = pgTable("lustre_rate_limits", { bucket: text("bucket").primaryKey(), count: integer("count").notNull(), resetsAt: timestamp("resets_at", { withTimezone: true }).notNull() });
export const lustreDevicePresence = pgTable("lustre_device_presence", { deviceID: uuid("device_id").primaryKey().references(() => lustreDevices.id), connectionID: uuid("connection_id").notNull(), connectedAt: timestamp("connected_at", { withTimezone: true }).notNull(), lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true }), agentVersion: text("agent_version").notNull(), heartbeatSequence: bigint("heartbeat_sequence", { mode: "number" }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() });
export const lustreDeviceCommands = pgTable("lustre_device_commands", { id: uuid("id").defaultRandom().primaryKey(), accountID: uuid("account_id").notNull().references(() => lustreAccounts.id), deviceID: uuid("device_id").notNull().references(() => lustreDevices.id), kind: text("kind").notNull(), payload: jsonb("payload").notNull(), status: text("status").notNull().default("pending"), result: jsonb("result"), createdAt, acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }) }, (table) => [index("lustre_device_commands_pending").on(table.deviceID, table.status, table.createdAt)]);
export const lustreDeviceJobStatus = pgTable("lustre_device_job_status", { deviceID: uuid("device_id").notNull().references(() => lustreDevices.id), jobID: uuid("job_id").notNull(), status: text("status").notNull(), progress: integer("progress"), downloadedBytes: bigint("downloaded_bytes", { mode: "number" }), totalBytes: bigint("total_bytes", { mode: "number" }), phase: text("phase"), attempts: integer("attempts").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() }, (table) => [uniqueIndex("lustre_device_job_status_device_job").on(table.deviceID, table.jobID), index("lustre_device_job_status_device_updated").on(table.deviceID, table.updatedAt)]);
