"use client";
import { useCallback, useEffect, useState } from "react";
type Presence = { state: "online" | "offline" | "neverConnected" | "revoked"; lastSeenAt: string | null; agentVersion: string | null };
type Device = { id: string; displayName: string; platform: string; agentVersion: string; createdAt: string; lastAuthenticatedAt: string | null; revokedAt: string | null; presence?: Presence };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) }, cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error?.message ?? "Unable to update devices."); return payload as T; }
export function DevicesView() {
  const [devices, setDevices] = useState<Device[]>([]); const [code, setCode] = useState<{ pairingCode: string; expiresAt: string } | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const next = (await api<{ devices: Device[] }>("/api/cloud/v1/devices")).devices; const presence = await Promise.all(next.map(async (device) => [device.id, await api<Presence>(`/api/cloud/v1/devices/${device.id}/presence`).catch(() => ({ state: "neverConnected", lastSeenAt: null, agentVersion: null } as Presence))] as const)); setDevices(next.map((device) => ({ ...device, presence: presence.find(([id]) => id === device.id)?.[1] }))); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load devices."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const pair = async () => { try { setCode(await api("/api/cloud/v1/pairing-challenges", { method: "POST" })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create a pairing code."); } };
  const rename = async (device: Device) => { const displayName = window.prompt("Device name", device.displayName); if (!displayName) return; try { await api(`/api/cloud/v1/devices/${device.id}`, { method: "PATCH", body: JSON.stringify({ displayName }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to rename device."); } };
  const revoke = async (device: Device) => { if (!window.confirm(`Revoke ${device.displayName}? This cannot be undone.`)) return; try { await api(`/api/cloud/v1/devices/${device.id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to revoke device."); } };
  return <section className="devices-panel"><div className="devices-actions"><div><h2>Pair a Mac</h2><p>Create a five-minute code, then run <code>lustre cloud pair &lt;code&gt; --name &quot;My Mac&quot;</code>.</p></div><button className="initiate-button" onClick={() => void pair()}>Create pairing code</button></div>{code && <div className="pairing-code"><strong>{code.pairingCode}</strong><span>Expires {new Date(code.expiresAt).toLocaleTimeString()}</span><button className="secondary-button" onClick={() => void navigator.clipboard.writeText(code.pairingCode)}>Copy code</button></div>}{error && <p className="form-error" role="alert">{error}</p>}<h2>Enrolled devices</h2>{loading ? <p>Loading devices…</p> : devices.length === 0 ? <div className="cloud-empty"><p>No Macs are paired yet.</p></div> : <ul className="cloud-device-list">{devices.map((device) => <li key={device.id}><div><strong>{device.displayName}</strong><p>{device.presence?.state === "online" ? "Online" : device.presence?.state === "neverConnected" ? "Never connected" : device.presence?.state === "revoked" ? "Revoked" : "Offline"} · {device.platform} · Agent {device.presence?.agentVersion ?? device.agentVersion}</p><small>{device.presence?.lastSeenAt ? `Last seen: ${new Date(device.presence.lastSeenAt).toLocaleString()}` : "No accepted heartbeat"}</small></div><div>{device.revokedAt ? <span>Revoked</span> : <><button className="secondary-button" onClick={() => void rename(device)}>Rename</button><button className="danger-button" onClick={() => void revoke(device)}>Revoke</button></>}</div></li>)}</ul>}</section>;
}
