"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityView } from "./activity-view";
import { DownloadsView } from "./downloads-view";
import type { DownloadJob } from "@/lib/download-job";
import type { JobAction } from "@/lib/job-actions";

type CloudJob = { id: string; displayName: string; preferredQualityLabel: string | null; status: DownloadJob["status"]; progress: number | null; downloadedBytes: number | null; totalBytes: number | null; phase: DownloadJob["transferPhase"] | null; attempts: number; updatedAt: string };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) }, cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error?.message ?? "Unable to contact the paired Mac."); return payload as T; }

export function CloudDashboardView({ deviceID, deviceName }: { deviceID: string; deviceName: string }) {
  const [jobs, setJobs] = useState<CloudJob[]>([]); const [error, setError] = useState<string | null>(null); const [view, setView] = useState<"downloads" | "activity">("downloads"); const [selectedJobID, setSelectedJobID] = useState<string | null>(null); const [url, setURL] = useState("");
  const refresh = useCallback(async () => { try { setJobs((await api<{ jobs: CloudJob[] }>(`/api/cloud/v1/devices/${deviceID}/jobs`)).jobs); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to refresh this Mac."); } }, [deviceID]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5_000); return () => window.clearInterval(timer); }, [refresh]);
  const command = async (body: Record<string, string>) => { await api(`/api/cloud/v1/devices/${deviceID}/commands`, { method: "POST", body: JSON.stringify(body) }); await refresh(); };
  const queue = async () => { try { await command({ kind: "queue_url", url }); setURL(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to queue download."); } };
  const mapped = useMemo<DownloadJob[]>(() => jobs.map((job) => ({ id: job.id, sourcePageURL: `lustre://job/${job.id}`, preferredQualityLabel: job.preferredQualityLabel ?? undefined, destination: "local", status: job.status, message: `${job.displayName} · synced from ${deviceName}`, progress: job.progress ?? undefined, downloadedBytes: job.downloadedBytes ?? undefined, totalBytes: job.totalBytes ?? undefined, transferPhase: job.phase ?? undefined, logs: [{ timestamp: job.updatedAt, level: ["failed", "verificationRequired"].includes(job.status) ? "error" : "info", message: `${job.status} reported by the paired Mac.` }], updatedAt: job.updatedAt })), [deviceName, jobs]);
  const action = async (job: DownloadJob, action: JobAction) => { if (!(["pause", "resume", "cancel", "retry"] as string[]).includes(action)) return; try { await command({ kind: "job_action", jobID: job.id, action }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to control download."); } };
  return <section className="devices-panel"><header className="devices-actions"><div><p className="eyebrow">Paired Mac</p><h2>{deviceName}</h2><p>Cloud control through the authenticated outbound agent connection.</p></div><div><button className="secondary-button" onClick={() => void refresh()}>Refresh</button><button className="secondary-button" onClick={() => setView(view === "downloads" ? "activity" : "downloads")}>{view === "downloads" ? "Activity" : "Downloads"}</button></div></header><div className="pairing-code"><input value={url} onChange={(event) => setURL(event.target.value)} placeholder="https://…" aria-label="Download URL" /><button className="initiate-button" disabled={!url.trim()} onClick={() => void queue()}>Queue download</button></div>{view === "downloads" ? <DownloadsView jobs={mapped} destinations={[]} error={error} selectedJobId={selectedJobID} onSelectJob={setSelectedJobID} onQueue={() => undefined} onAction={action} /> : <ActivityView jobs={mapped} destinations={[]} error={error} onOpenDownloads={(id) => { setSelectedJobID(id ?? null); setView("downloads"); }} />}</section>;
}
